spring :
  datasource:
    url: jdbc:mysql://localhost:3306/userservice?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 7999389177
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true