spring :
  datasource:
    url: jdbc:mysql://localhost:3306/userservice?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Prashant@1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true